#    _____ __                  __    _
#   / ___// /_____ ___________/ /_  (_)___
#   \__ \/ __/ __ `/ ___/ ___/ __ \/ / __ \
#  ___/ / /_/ /_/ / /  (__  ) / / / / /_/ /
# /____/\__/\__,_/_/  /____/_/ /_/_/ .___/
#                                 /_/

[directory]
read_only = " "

[jobs]
symbol_threshold = 1
number_threshold = 2
symbol = "✦ "
format = "[$symbol$number]($style)"

[os]
disabled = true
format = "[$symbol]($style) "

[package]
symbol = ""

[shell]
disabled = false
bash_indicator = ""
nu_indicator = "ν "
powershell_indicator = "PS "
xonsh_indicator = " "
zsh_indicator = "z "
style="cyan italic"
format = "$indicator($style)"

[shlvl]
disabled = false
threshold = 4
symbol = "↓"
format = "[$symbol]($style) "

#     __
#    / /   ____ _____  ____ ___  ______ _____ ____  _____
#   / /   / __ `/ __ \/ __ `/ / / / __ `/ __ `/ _ \/ ___/
#  / /___/ /_/ / / / / /_/ / /_/ / /_/ / /_/ /  __(__  )
# /_____/\__,_/_/ /_/\__, /\__,_/\__,_/\__, /\___/____/
#                   /____/            /____/

[cmake]
symbol = "C "
#symbol = " "

[dotnet]
format = "[$symbol($version )]($style)"
symbol = "•NET "
#symbol = " "

[golang]
symbol = "GO "
#symbol = "ﳑ "

[java]
symbol = "Java "
#symbol = " "

[nodejs]
format = "via [$symbol]($style)"
#symbol = "NodeJS "
symbol = "JS "
#symbol = " "

[lua]
symbol = "Lua "
#symbol = " "

[perl]
symbol = "Perl "

[php]
symbol = "PHP "

[python]
symbol = "Py "
#symbol = " "
#symbol = " "

[ruby]
symbol = "Ruby "
#symbol = " "
#symbol = " "

[rust]
symbol = "Rs "
#symbol = " "

#    ____  _____    _____                 __          __
#   / __ \/ ___/   / ___/__  ______ ___  / /_  ____  / /____
#  / / / /\__ \    \__ \/ / / / __ `__ \/ __ \/ __ \/ / ___/
# / /_/ /___/ /   ___/ / /_/ / / / / / / /_/ / /_/ / (__  )
# \____//____/   /____/\__, /_/ /_/ /_/_.___/\____/_/____/
#                     /____/

[os.symbols]
Arch = ""
Linux = ""
Macos = ""
Mint = ""
Raspbian = ""
#Void = "" # really? no void?
Windows = ""
Unknown = ""
