theme = "val-onedark"

[editor]
auto-completion = false
auto-format = false
auto-pairs = false
idle-timeout = 2000

[editor.lsp]
display-messages = true

[editor.smart-tab]
enable = false

[keys.insert]
C-space = "completion"

