
[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
shebangs = ["sh", "bash", "/usr/bin/bash", "/usr/bin/sh"]

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c-sharp"
indent = { tab-width = 4, unit = "\t" }
language-server = { commmand = "omnisharp", args = [ "--languageserver", "--stdio" ] }

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "php"
indent = { tab-width = 4, unit = "\t" }
shebangs = ['php', '/usr/bin/php']

[[language]]
name = "python"
indent = { tab-width = 4, unit = "\t" }
shebangs = ['python', '/usr/bin/python']

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }

