
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c-sharp"
language-servers = [ "omnisharp --languageserver --stdio" ]

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }
file-types = [ "html", { suffix = "html.tera" } ]

[[language]]
name = "java"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "php"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "sql"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "xml"
indent = { tab-width = 4, unit = "\t" }

